config/routes.rb
Rails.application.routes.draw do
  resources :trails
  post '/trails/get_weather'
  post '/trails/get_trails'
  get "/app/views/trails/login.html.erb", to: "trails#login", as: "login"
  
  

  root 'trails#index' # must comment out if wanting to initially test cucumber

  

end

app/models/trail.rb
class Trail < ActiveRecord::Base
    
    def self.search(search)
        if search
            where(["name LIKE ?", "%#{search}%"])
        else
            all
        end
    end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  include ActionView::Helpers::DateHelper
  before_action :set_trail, only: [:show, :edit, :update, :destroy]

  # GET /trails
  # GET /trails.json
  def index
    @trails = Trail.all
   
    #this is only to update the database when necessary
    #if (params[:debug] == "get_trails")then
      #@trails.each do |trail|
        #trail.delete
      #end
      #raw_response = get_trails();
      #places = raw_response["places"]
      #places.each do |place|
        #activityhash = place["activities"][0]
        #if(place["lat"] < 38.629451 || place["lon"] > -104.496141 || place["lat"] > 39.169331 || place["lon"] < -105.391381)then
          
        #else
         #Trail.create({:name => activityhash["name"], :nature => "hike", :difficulty => activityhash["length"].to_s, :latitude => place["lat"], :longitude => place["lon"], :comment => "", :note => activityhash["description"]})
        #end
      #end
    #end
    
    #return value of 0 = just trails
    #retunr value of 1 = just infoboxes
    #return value of 2 = both infoboxes and weather circles
    @map_features = get_map_features(params[:map_features])

    #these variables house the on-map weather display details
    #if they are empty, then no weather circles will be put on the map
    @weather_count = 0
    @weather_circles_count = 0
    @snow_array = Array.new
    @rain_array = Array.new
    @fog_array = Array.new
    
    #puts each trail onto the map
    @markers = Gmaps4rails.build_markers(@trails) do |trail, marker|
    marker.lat trail.latitude
    marker.lng trail.longitude
    marker.picture({"url" => view_context.image_path(trail.nature+'.png'), "width" => 32, "height" => 47})
    
    #If you want to see any weather details at all, show_me_weather should be true
    if (@map_features > 0) then
      
    trailweather = get_weather(trail.latitude, trail.longitude)
      
      #in the event of an API Misshap, don't attempt to proceed
      if (trailweather["currentobservation"].nil? || trailweather == "GPS location out of bounds" || trailweather.nil?)then
          marker.infowindow '<div><center>' + trail.name + '</center>
                      <table id ="' + trail.name + '_weather_infobox"><center>
                        <th>Overview</th>
                        <th>Now</th>
                        <tr>
                        <td>Weather API Error, please try again later</td>
                        </tr>
                      </table>
                      </center>
                      </div>'
      else
    
        now = trailweather["currentobservation"]
        data = trailweather["data"]
        weekimage = data["iconLink"]
        weektemp = data["temperature"]
        weekweather = data["weather"]
        
        #wind is often reporting 999 degrees, thats probably not right, so I added this
        if now["Windd"].to_i > 360 || now["Windd"].to_i < 0 then
          now["Windd"] = "N/A"
        end
    
        #If you want to see weather overlaid on the map, show_me_weather should be true
        if (@map_features == 2) then
          weather_code = get_inclimate(weekweather[0])
          if weather_code == 0 then
            @snow_array.push({"lat" => trail.latitude, "lng" => trail.longitude, "radius" => 2500})
          elsif weather_code == 1 then
            @rain_array.push({"lat" => trail.latitude, "lng" => trail.longitude, "radius" => 2500})
          elsif weather_code == 2 then
          @fog_array.push({"lat" => trail.latitude, "lng" => trail.longitude, "radius" => 2500})
          end
        end
    
        marker.infowindow '<div><center>' + trail.name + '</center>
                      <table id ="' + trail.name + '_weather_infobox"><center>
                        <th>Overview</th>
                        <th>Now</th>
                        <tr>
                        <td>
                          <table>
                          <tr><td><img src='+ weekimage[0] +' style="width:150px;height:125px;"></td></tr>
                          <tr><td>C: ' +    now["Temp"] +'&deg, ' + weektemp[0] + '&deg / ' + weektemp[1] + '&deg</td></tr>
                          </table>
                        </td>
                          <td>
                            <table>
                              <tr><td>' +  weekweather[0] + '</td></tr>
                              <tr><td>Humidity: ' +  now["Relh"] + '</td></tr>
                              <tr><td>Visibility: ' +  now["Visibility"] + 'mi</td></tr>
                              <tr><td>' +  now["Date"] + '</td></tr>
                              <td>Wind: ' + now["Winds"] + 'mph by ' + now["Windd"] + '&deg</td>
                              <tr><td><a href="'+ trail_path(trail) +'">More Info</a></td></tr>
                            </table>
                          </td>
                        </tr>
                      </table>
                      </center>
                      </div>'
          @weather_count += 1
      end
      
    else
      #for when no weather details are desired, this simply puts the name instead
      marker.infowindow '<a href="'+ trail_path(trail) +'"> ' + trail.name + '</a>'
    end
    
    if(params[:search])then
      @trails_search_data = Trail.search(params[:search])
    else
      @trails_search_data = []
    end
    
    #how many weather circles are there
    @weather_circles_count = @snow_array.count + @rain_array.count + @fog_array.count
    end
  end
  
  # this function returns a hash that looks like this http://forecast.weather.gov/MapClick.php?lat=38.989055&lon=-104.898360&FcstType=json
  def get_weather lat,long
    if (lat.to_f < 38.629451 || long.to_f > -104.496141 || lat.to_f > 39.169331 || long.to_f < -105.391381)then
      return "GPS location out of bounds"
    else
    address = "http://forecast.weather.gov/MapClick.php?lat=" + lat.to_s + "&lon=" + long.to_s + "&FcstType=json";
    weather = HTTP.get(address)
    weatherhash = JSON.parse(weather)
    return weatherhash
    end
  end
  
  #this function doesn't actually get called anymore, its just there to update the db when necessary.
  #def get_trails
    #response = Unirest.get "https://trailapi-trailapi.p.mashape.com/?limit=80&q[activities_activity_type_name_eq]=hiking&q[city_cont]=Colorado+Springs&radius=80",headers:{"X-Mashape-Key" => "ktoxroBJpimshiVYcNS5rEJ2BuS3p1wGr2Fjsn5tnV3C0tYu87","Accept" => "text/plain"}
    #trails = response.body
    #return trails
  #end
  
  #for now this is useless
  #def has_been_an_hour last_updated
    #one_hour = ((60.minutes).to_formatted_s(:number)).to_i
    #one_hour_after = (last_updated).to_i + (one_hour).to_i
    #now = ((Time.now).to_formatted_s(:number)).to_i
    
    #if (now > one_hour_after)then
    #  return true
    #else
      #return false
    #end
  #end
  
  # 0 = snow, 1 = rain, 2 = fog, -1 = nothing in particular
  def get_inclimate currentweather
    currentweather = currentweather.to_s
    if currentweather.match(/snow/i) then
      return 0
    elsif currentweather.match(/rain/i) || currentweather.match(/thunder/i) || currentweather.match(/lightning/i) then
      return 1
    elsif currentweather.match(/fog/i) then
      return 2
    else
      return -1
    end
  end
  
  def get_map_features features_controll
    if(features_controll)then
      if(features_controll == "trails_only")then
        return 0
      elsif(features_controll == "weather_details")then
        return 1
      elsif(features_controll == "weather_details_plusoverlay")then
        return 2
      end
    else
      return 0
    end
  end

  # GET /trails/1c
  # GET /trails/1.json
  def show
    @trails = @trail
    @snow_array = Array.new
    @rain_array = Array.new
    @fog_array = Array.new
    
    if params[:debug] == "delete_comments" then
      @trail.update(comment: "")
    end
    
    trailweather = get_weather(@trail.latitude, @trail.longitude)
    @now = trailweather["currentobservation"]
    @data = trailweather["data"]
    @time = trailweather["time"]
    @weekimage = @data["iconLink"]
    @weektemp = @data["temperature"]
    @weekweather = @data["weather"]
    #raw_hazard = @data["hazardUrl"]
    #@hazardoutlook = raw_hazard[0].gsub(/amp;/, "")
    #@hazardoutlook2 = raw_hazard[1].gsub(/amp;/, "")
    
    @markers = Gmaps4rails.build_markers(@trails) do |trail, marker|
    marker.lat trail.latitude
    marker.lng trail.longitude
    marker.picture({"url" => view_context.image_path(trail.nature+'.png'), "width" => 32, "height" => 47})
    @weather_code = get_inclimate(@weekweather[0])
      if @weather_code == 0 then
        @snow_array.push({"lat" => trail.latitude, "lng" => trail.longitude, "radius" => 2500})
      elsif @weather_code == 1 then
        @rain_array.push({"lat" => trail.latitude, "lng" => trail.longitude, "radius" => 2500})
      elsif @weather_code == 2 then
        @fog_array.push({"lat" => trail.latitude, "lng" => trail.longitude, "radius" => 2500})
      end
    end
    if params[:comment] then
      new_comment = params[:comment].to_s
      if (new_comment != "")then
      @trail.update(comment: @trail.comment + '///' + Time.now.to_s + ' ' + new_comment + ' ')
      end
    end
    @all_comments = @trail.comment.split("///")
  end

  # GET /trails/new
  def new
    @trail = Trail.new
  end

  # GET /trails/1/edit
  def edit
  end

  # POST /trails
  # POST /trails.json
  def create
    @trail = Trail.new(trail_params)

    respond_to do |format|
      if @trail.save
        format.html { redirect_to @trail, notice: 'Trail was successfully created.' }
        format.json { render :show, status: :created, location: @trail }
      else
        format.html { render :new }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trails/1
  # PATCH/PUT /trails/1.json
  def update
    respond_to do |format|
      if @trail.update(trail_params)

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/trails/_form.html.erb
<%= form_for(@trail) do |f| %>
  <% if @trail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trail.errors.count, "error") %> prohibited this trail from being saved:</h2>

      <ul>
      <% @trail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nature %><br>
    <%= f.text_field :nature %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.text_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trails/edit.html.erb
<h1>Editing Trail</h1>

<%= render 'form' %>

<%= link_to 'Show', @trail %> |
<%= link_to 'Back', trails_path %>

app/views/trails/index.html.erb
<!-- Facebook account kit JDK -->
<script src="https://sdk.accountkit.com/en_US/sdk.js"></script>

<script src="//maps.google.com/maps/api/js?key=AIzaSyA26LRVD8pSUIOQRUcMETPbK8c0fNgp7wQ"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<p id="notice"><%= notice %></p>
<!-- http://yume.hacca.jp/koiki/css/table/table.htm -->
<center>
<table class="sample_04" style='width: 100%;'>
  <td style='width: 25%;'>
    <center>All trails</center>
    <div class="table-wrapper">
      <div class="table-scroll-all">
        <table class="sample_04", id="popular">
        <th>By name</th>
        <tbody>
          <% @trails.each do |trail| %>
          <tr>
            <td><%= link_to "#{trail.name}", trail_path(trail), :id => 'trail_link'%></td>
          </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </td>
  <td style='width: 50%;'>
    <div id="map" style='width: 100%; height: 400px;'></div>
  </td>
  <td><center>Tools</center>
    <table class="sample_04">
      <!--signup start -->
      <th> Sign in or Sign up </th>
      <tr>
        <td>
          <script>
            window.fbAsyncInit = function() {
              FB.init({
                appId      : '118495718699021',
                cookie     : true,
                xfbml      : true,
                version    : 'v2.8'
              });
              FB.AppEvents.logPageView();   
            };
            (function(d, s, id){
               var js, fjs = d.getElementsByTagName(s)[0];
               if (d.getElementById(id)) {return;}
               js = d.createElement(s); js.id = id;
               js.src = "//connect.facebook.net/en_US/sdk.js";
               fjs.parentNode.insertBefore(js, fjs);
             }(document, 'script', 'facebook-jssdk'));
          </script>
          <div id="fb-root"></div>
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9&appId=118495718699021";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
          <div class="fb-login-button" data-max-rows="1" data-size="small" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="true" data-use-continue-as="true" id = "fb-login-button"></div>
          <div class="fb-like" data-href="http://cs3300-zeklaus.c9users.io/" data-layout="standard" data-action="like" data-size="small" data-show-faces="false" data-share="true" id = "fb-like"></div>        
          </td>
      </tr>
      <!--signup end -->
      <tr>
        <td>
        </td>
      </tr>
      <th>Search</th>
      <tr>
        <td>
          <!--search bar field start-->
          <%= form_tag trails_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :id => "submit_button"%>
          <% end %>
          <!--search bar field end-->
        </td>
      <tr>
        <td>
          <div class="table-wrapper">
            <div class="table-scroll-search">
              <table class="sample_04", id="search-results">
                <th>Search Results</th>
                <tbody>
                 <% @trails_search_data.each do |trail| %>
                  <tr>
                    <td><%= link_to "#{trail.name}", trail_path(trail), :id => 'trail_link_search'%></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <th>
          Map tools
        </th>
      </tr>
      <tr><td id="map_features_none"><%= link_to'Show Just Trails', trails_path(:map_features => "trails_only") %></td></tr>
      <tr><td id="map_features_weather"><%= link_to 'Show Weather Details For Each Trail', trails_path(:map_features => "weather_details")%></td></tr>
      <tr><td id="map_features_circles"><%= link_to 'Show Inclimate Weather on Map', trails_path(:map_features => "weather_details_plusoverlay")%></td></tr>
      <tr><td id="trail_weather_count">Map has weather details for <%= @weather_count %> trails</td></tr>
      <tr><td id="trail_weather_circle_count">Map has weather a weather overlay for <%= @weather_circles_count %> trails</td></tr>
    </table>
  </td>
</table>
<div class="loader" style="display:none"></div>

<!--<table class="sample_04">-->
<!--  <th>Debug</th>-->
<!--  <tr><td><%= link_to 'Test Weather Circles', trails_path(:debug => "weather")%></td></tr>-->
<!--  <tr><td><%= link_to 'Get Trails', trails_path(:debug => "get_trails")%></td></tr>-->
<!--  <tr><td><p><%= @trail_data %></p></td></tr>-->
<!--</table>-->

</center>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @markers.to_json %>);
  
  myoverlay = new google.maps.OverlayView();
  myoverlay.draw = function () {this.getPanes().markerLayer.id = 'markers_overlay';};
  myoverlay.setMap(handler.getMap());
  
  //Weather overlay
  snow_circles = handler.addCircles(<%=raw @snow_array.to_json %>, {fillColor: '#FFFFFF', fillOpacity: 0.6});
  rain_cirlces = handler.addCircles(<%=raw @rain_array.to_json %>, {fillColor: '#0000FF', fillOpacity: 0.6});
  fog_cirlces = handler.addCircles(<%=raw @fog_array.to_json %>, {fillColor: '#B0C4DE', fillOpacity: 0.6});
  //Weather overlay
  
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
  
  map_features_controller_none = document.getElementById("map_features_none");
  map_features_controller_weather = document.getElementById("map_features_weather");
  map_features_controller_circles = document.getElementById("map_features_circles");
  
  map_features_controller_none.onclick = function() {activate_spinner()};
  map_features_controller_weather.onclick = function() {activate_spinner()};
  map_features_controller_circles.onclick = function() {activate_spinner()};
  
  function activate_spinner()
  {
    loader = document.getElementsByClassName("loader");
    loader[0].style = "display:all;";
  }
  function deactivate_spinner()
  {
    loader = document.getElementsByClassName("loader");
    loader[0].style = "display:none;";
  }
  
</script>

</body>

app/views/trails/login.html.erb
<h1>New Trail</h1>

<body>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '118495718699021',
      xfbml      : true,
      version    : 'v2.8'
    });
    FB.AppEvents.logPageView();
    
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
    
    <div id="fb-root"></div>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=118495718699021";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    
    function login(){
      FB.login(function(response){
        if(response.status == 'connected'){
        document.getElementById('status').innerHTML = 'Welcome! Login successful';
      } else if (response.status == 'not_authorized'){
        document.getElementById('status').innerHTML = 'Not logged in.';
      } else {
        document.getElementById('status').innerHTML = 'Facebook login failed.';
      }
      })
    }
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

</body>

app/views/trails/new.html.erb
<h1>New Trail</h1>

<%= render 'form' %>

<%= link_to 'Back', trails_path %>

app/views/trails/show.html.erb
<!--https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_templates_cv&stacked=h-->
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}

div.scroll {
    height: 360px;
    overflow: scroll;
}

</style>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <div class="w3-container">
            <h2 class="w3-text-black w3-padding-16"><%= @trail.name %></h2>
          </div>
          <div id="map" style='width: 100%; height: 400px;'></div>
        </div>
        <div class="w3-container">
          <p>
            <strong>Type:</strong>
            <%= @trail.nature %>
          </p>
          
          <p>
            <strong>Length:</strong>
            <%= @trail.difficulty %> miles
          </p>
          
          <p>
            <strong>Latitude:</strong>
            <%= @trail.latitude %>
          </p>
          
          <p>
            <strong>Longitude:</strong>
            <%= @trail.longitude %>
          </p>
        </div>
      </div><br>
      
      <div class="w3-white w3-text-grey w3-card-4">
        <h3 class="w3-text-grey w3-padding-16"><i class="fa fa-exclamation fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Administrator's Note</h2>
          <tr>
            <td>
              <%= @trail.note %>
            </td>
          </tr>
      </div><br>  
      
      <div class="w3-white w3-text-grey w3-card-4">
        <h3 class="w3-text-grey w3-padding-16"><i class="fa fa-comment fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Comments</h2>
          <tr>
            <td>
            <!--comment field start-->
            <%= form_tag trail_path(@trail), :method => 'get' do %>
              <%= text_field_tag :comment, params[:comment] %>
              <%= submit_tag "Add Comment", :id => "submit_button"%>
            <% end %>
            <!--comment field end-->
              <% @all_comments.each do |comment| %>
                <p><%= comment %></p>
              <% end %>
              <%= link_to "delete comments for this trail", trail_path(@trail, :debug => "delete_comments"), :id => 'trail_delete_comments'%>
            </td>
          </tr>
      </div><br>  

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
    
      <div class="w3-container w3-card-2 w3-white w3-margin-bottom">
        <h3 class="w3-text-grey w3-padding-16"><i class="fa fa-cloud fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Current Weather</h2>
        <div class="w3-container scroll">
          <h5 class="w3-opacity"><b>Condition: <%=@now["Weather"]%></b></h5>
          <img src=<%= @weekimage[0] %> style="width:150px;height:125px;", id ="weather_image">

          <p><strong>Temperature:</strong> <%=@now["Temp"]%>&deg F</p>
          <p><strong>Wind Chill:</strong> <%=@now["WindChill"]%>&deg F</p>
          <p><strong>Dewpoint:</strong> <%=@now["Dewp"]%>&deg F</p>
            <p><strong>Humidity:</strong> <%=@now["Relh"]%>%</p>
            <p><strong>Wind:</strong> <%=@now["Winds"]%> mph</p>
            <p>Direction: <%=@now["Windd"]%>&deg</p>
            <p>Gust: <%=@now["Gust"]%> mph</p>
            <p><strong>Visibility:</strong> <%=@now["Visibility"]%> mi</p>
            <p><strong>Barometric</strong> Pressure: <%=@now["SLP"]%> in</p>
            <p><strong>Last Updated:</strong> <%=@now["Date"]%></p>
            <p><strong>Weather Warnings and Hazards:</strong></p>
                 <!--<a href=<#%= @hazardoutlook %>><#%=@data["hazard"][0]%></a> -->
                 <!--<a href=<#%= @hazardoutlook2 %>><#%=@data["hazard"][1]%></a> -->
          <hr>
        </div>

      </div>

      <div class="w3-container w3-card-2 w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Weather Forecast</h2>
          <div class="scroll">
            <% @time["startPeriodName"].each_with_index do |element, i| %>
            <div class="w3-container">
              <p><%=@time["startPeriodName"][i]%>: <%=@data["text"][i]%></p>
              <p><img src=<%= @weekimage[i] %> style="width:150px;height:125px;"></p>
              <hr>
            </div>
            <% end %>
          </div>
      </div>

    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>

<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p>
  <%= link_to 'Back', trails_path %>
  </p>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

</body>
</html>

<script src="//maps.google.com/maps/api/js?key=AIzaSyA26LRVD8pSUIOQRUcMETPbK8c0fNgp7wQ"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<p id="notice"><%= notice %></p>




<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @markers.to_json %>);
  
  myoverlay = new google.maps.OverlayView();
  myoverlay.draw = function () {this.getPanes().markerLayer.id = 'markers_overlay';};
  myoverlay.setMap(handler.getMap());
  
  //Weather overlay
  snow_circles = handler.addCircles(<%=raw @snow_array.to_json %>, {fillColor: '#FFFFFF', fillOpacity: 0.6});
  rain_cirlces = handler.addCircles(<%=raw @rain_array.to_json %>, {fillColor: '#0000FF', fillOpacity: 0.6});
  fog_cirlces = handler.addCircles(<%=raw @fog_array.to_json %>, {fillColor: '#B0C4DE', fillOpacity: 0.6});
  //Weather overlay
  
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(15);
  });
</script>